const { DependencyContainer } = require('gell');
const { init } = require('gell/future');

const sessionAuthority = require('gell-web/authority/jwt');
const userAuthority = require('gell-web/authority/user');

const idm = require('./gell-actor/static/authority-identity');
const userIndex = require('./gell-actor/static/index-user');

const { OAuth2Client } = require('google-auth-library');
const calendar = require('@googleapis/calendar');

const ISSUER = {
	id: 'https://bluehourholdings.com',
	signingKey: 'abc123',  // TODO: this should be generated by the ecosystem
	organization: 'sunshine'
}

let [$idm] = init(idm('gello!'));
let [$userIndex] = init(userIndex(['operator']));
let [$userAuthority] = init(userAuthority());
let [$sessionAuthority] = init(sessionAuthority(ISSUER));

let deps = new DependencyContainer({
	$idm,
	$sessionAuthority,
	$userAuthority,

	$userIndex,

	oauthClient: new OAuth2Client(
		process.env.GOOGLE_CLIENT_ID,
		process.env.GOOGLE_CLIENT_SECRET,
		'http://localhost:12700/google/callback/authz',
	),
	calendar: calendar.calendar('v3')
});

module.exports = deps;
